-- MySQL Script generated by MySQL Workbench
-- Sun Feb 18 12:58:39 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema estudo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema estudo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `estudo` DEFAULT CHARACTER SET utf8 ;
USE `estudo` ;

-- -----------------------------------------------------
-- Table `estudo`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estudo`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(220) NOT NULL,
  `email` VARCHAR(220) NOT NULL,
  `password` VARCHAR(220) NOT NULL,
  `recuperar_senha` VARCHAR(50) NULL,
  `foto` VARCHAR(220) NULL,
  `niveis_acesso_id` INT(11) NOT NULL,
  `situacoes_user_id` INT(11) NOT NULL,
  `created` DATETIME NOT NULL,
  `modified` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estudo`.`rotas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estudo`.`rotas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_rota` VARCHAR(12) NOT NULL DEFAULT 'Para Editar',
  `created` DATETIME NOT NULL,
  `modified` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estudo`.`fins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estudo`.`fins` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_fim` VARCHAR(25) NOT NULL,
  `created` DATETIME NOT NULL,
  `modified` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estudo`.`varas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estudo`.`varas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_vara` VARCHAR(10) NOT NULL,
  `created` DATETIME NOT NULL,
  `modified` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estudo`.`mandados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estudo`.`mandados` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `origem` INT(6) NOT NULL DEFAULT 0,
  `processo` VARCHAR(45) NOT NULL,
  `destinatario` VARCHAR(220) NOT NULL,
  `vara_id` INT(11) NOT NULL,
  `fim_id` INT(11) NOT NULL,
  `rota_id` INT(11) NOT NULL,
  `user_id` INT(11) NOT NULL,
  `created` DATETIME NOT NULL,
  `modified` DATETIME NULL,
  `users_id` INT NOT NULL,
  `rotas_id` INT NOT NULL,
  `fins_id` INT NOT NULL,
  `varas_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_mandados_users_idx` (`users_id` ASC),
  INDEX `fk_mandados_rotas1_idx` (`rotas_id` ASC),
  INDEX `fk_mandados_fins1_idx` (`fins_id` ASC),
  INDEX `fk_mandados_varas1_idx` (`varas_id` ASC),
  CONSTRAINT `fk_mandados_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `estudo`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mandados_rotas1`
    FOREIGN KEY (`rotas_id`)
    REFERENCES `estudo`.`rotas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mandados_fins1`
    FOREIGN KEY (`fins_id`)
    REFERENCES `estudo`.`fins` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mandados_varas1`
    FOREIGN KEY (`varas_id`)
    REFERENCES `estudo`.`varas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estudo`.`devolutivas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estudo`.`devolutivas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `origem` INT(6) NOT NULL,
  `processo` VARCHAR(45) NOT NULL,
  `destinatario` VARCHAR(220) NOT NULL,
  `vara_id` INT(11) NOT NULL,
  `fim_id` INT(11) NOT NULL,
  `rota_id` INT(11) NOT NULL,
  `user_id` INT(11) NOT NULL,
  `created` DATETIME NOT NULL,
  `modified` DATETIME NULL,
  `recibo` VARCHAR(45) NULL,
  `mandados_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_devolutivas_mandados1_idx` (`mandados_id` ASC),
  CONSTRAINT `fk_devolutivas_mandados1`
    FOREIGN KEY (`mandados_id`)
    REFERENCES `estudo`.`mandados` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
